spring:
  application:
    name: xd-springcloud-config-server
  profiles:
    active: dev
server:
  port: 5000
management:
  security:
    enabled: false
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://server1:8001/eureka/,http://server2:8002/eureka/,http://server3:8003/eureka/

